const SCHEME_WIDTH = 1200,
  SCHEME_HEIGHT = 630,
  TIME_MENU_WIDTH = 240,
  TIME_MENU_HEIGHT = 200,
  TIME_MENU_HEIGHT_MOBILE = 160,
  TIME_MENU_WIDTH_MOBILE = 200,
  MOBILE_BREAKPOINT = 640;

export {
  SCHEME_WIDTH,
  SCHEME_HEIGHT,
  TIME_MENU_HEIGHT,
  TIME_MENU_WIDTH,
  TIME_MENU_HEIGHT_MOBILE,
  TIME_MENU_WIDTH_MOBILE,
  MOBILE_BREAKPOINT,
};
